Controllers/FiskGuideController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Digitala_FiskGuiden.Models;

namespace Digitala_FiskGuiden.Controllers
{
    public class FiskGuideController : Controller
    {
        private readonly FiskContext _context;

        public FiskGuideController(FiskContext context)
        {
            _context = context;
        }

        // GET: FiskGuide
        public async Task<IActionResult> Index()
        {
            var fiskContext = _context.Fiskar.Include(f => f.Klass);


            // TRY CATCH SOM TAR DIG TILL VID FEL, SE ENFULSIDACONTROLLER SAMT INDEX
            try
            {
                return View(await fiskContext.ToListAsync());
            }
            catch (Exception)
            {
                return RedirectToAction("EnFulErrorSida");
            }

            
        }

        // GET: FiskGuide/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fisk = await _context.Fiskar
                .Include(f => f.Klass)
                .FirstOrDefaultAsync(m => m.FiskId == id);
            if (fisk == null)
            {
                return NotFound();
            }
            // TRY CATCH SOM TAR DIG TILL VID FEL, SE ENFULSIDACONTROLLER SAMT INDEX

            try
            {
               return View(fisk);
            }
            catch (Exception)
            {
                return RedirectToAction("EnFulErrorSida");
            }

            
        }

        // GET: FiskGuide/Create
        public IActionResult Create()
        {
            ViewData["KlassId"] = new SelectList(_context.Klasser, "KlassId", "FiskKlass");
            return View();
        }

        // POST: FiskGuide/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FiskId,Art,Fakta,KlassId")] Fisk fisk)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fisk);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["KlassId"] = new SelectList(_context.Klasser, "KlassId", "KlassId", fisk.KlassId);
            try
            {
                return View(fisk);
            }
            catch (Exception)
            {
                return RedirectToAction("EnFulErrorSida");
            }
        }

        // GET: FiskGuide/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fisk = await _context.Fiskar.FindAsync(id);
            if (fisk == null)
            {
                return NotFound();
            }
            ViewData["KlassId"] = new SelectList(_context.Klasser, "KlassId", "FiskKlass", fisk.KlassId);
            return View(fisk);
        }

        // POST: FiskGuide/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FiskId,Art,Fakta,KlassId")] Fisk fisk)
        {
            if (id != fisk.FiskId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fisk);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FiskExists(fisk.FiskId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["KlassId"] = new SelectList(_context.Klasser, "KlassId", "KlassId", fisk.KlassId);
            return View(fisk);
        }

        // GET: FiskGuide/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fisk = await _context.Fiskar
                .Include(f => f.Klass)
                .FirstOrDefaultAsync(m => m.FiskId == id);
            if (fisk == null)
            {
                return NotFound();
            }

            return View(fisk);
        }

        // POST: FiskGuide/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fisk = await _context.Fiskar.FindAsync(id);
            _context.Fiskar.Remove(fisk);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FiskExists(int id)
        {

            return _context.Fiskar.Any(e => e.FiskId == id);
        }
    }
}

Views/FiskGuide/Create.cshtml
@model Digitala_FiskGuiden.Models.Fisk

@{
    ViewData["Title"] = "Create";
}
<!DOCTYPE html>
<html>
<head>
    <link href="~/css/MinStil.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

</head>
<body>
    <h1>Fiskguide</h1>

    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Art" class="control-label"></label>
                    <input asp-for="Art" class="form-control" />
                    <span asp-validation-for="Art" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Fakta" class="control-label"></label>
                    <input asp-for="Fakta" class="form-control" />
                    <span asp-validation-for="Fakta" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="KlassId" class="control-label"></label>
                    <select asp-for="KlassId" class="form-control" asp-items="ViewBag.KlassId"></select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Skapa" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Tillbaka</a>
    </div>
</body>
</html>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/FiskGuide/Delete.cshtml
@model Digitala_FiskGuiden.Models.Fisk

@{
    ViewData["Title"] = "Delete";
}

<h1>Radera</h1>

 
<div>
    <h4>Fisk</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Art)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Art)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fakta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fakta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Klass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Klass.KlassId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FiskId" />
        <input type="submit" value="Radera" class="btn btn-danger" /> |
        <a asp-action="Index">Gå tillbaka</a>
    </form>
</div>

Views/FiskGuide/Details.cshtml
@model Digitala_FiskGuiden.Models.Fisk

@{
    ViewData["Title"] = "Details";
}

<h1>Detaljer</h1>

<div>
    <h4>Fisk</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Art)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Art)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fakta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fakta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Klass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Klass.KlassId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.FiskId">Ändra</a> |
    <a asp-action="Index">Gå tillbaka</a>
</div>

Views/FiskGuide/Edit.cshtml
@model Digitala_FiskGuiden.Models.Fisk

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Fisk</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FiskId" />
            <div class="form-group">
                <label asp-for="Art" class="control-label"></label>
                <input asp-for="Art" class="form-control" />
                <span asp-validation-for="Art" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fakta" class="control-label"></label>
                <input asp-for="Fakta" class="form-control" />
                <span asp-validation-for="Fakta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KlassId" class="control-label"></label>
                <select asp-for="KlassId" class="form-control" asp-items="ViewBag.KlassId"></select>
                <span asp-validation-for="KlassId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Spara" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Gå tillbaka</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/FiskGuide/Index.cshtml
@model IEnumerable<Digitala_FiskGuiden.Models.Fisk>

@{
    ViewData["Title"] = "Index";
}

<nav class="navbar navbar-expand-sm bg-success navbar-dark">
    <a class="navbar-brand" href="#">Digitala Fiskguiden</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
            <li>@Html.ActionLink("Hem", "Index", "Home")</li> &nbsp;&nbsp; &nbsp;&nbsp;
            <li>@Html.ActionLink("Fiskguide", "Index", "FiskGuide")</li> &nbsp;&nbsp; &nbsp;&nbsp;
            <li>@Html.ActionLink("Klasser", "Index", "Klasser")</li>
        </ul>
    </div>
</nav>

<h1>Fiskguide</h1>

<p>
    <a asp-action="Create">Lägg till fisk</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Art)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fakta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Klass)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Art)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fakta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Klass.FiskKlass)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.FiskId">Ändra</a> 
                <a asp-action="Details" asp-route-id="@item.FiskId">Detaljer</a> 
                <a asp-action="Delete" asp-route-id="@item.FiskId">Radera</a>
            </td>
        </tr>
}
    </tbody>
</table>